// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlH6iMnjWfpHr7sAzIImQPom6pVO__SmE',
    appId: '1:790628540474:web:e3f9b523ff698b6a1a9503',
    messagingSenderId: '790628540474',
    projectId: 'waiterbook',
    authDomain: 'waiterbook.firebaseapp.com',
    storageBucket: 'waiterbook.appspot.com',
    measurementId: 'G-8RJFGYR3Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOyQ5Wl-_j8qdVu04eYNt2lEizJxq7BlY',
    appId: '1:790628540474:android:f66283a8fa7db61e1a9503',
    messagingSenderId: '790628540474',
    projectId: 'waiterbook',
    storageBucket: 'waiterbook.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDw7QRcN7pQ877s2HtAbzCjPyVL_qwEl3c',
    appId: '1:790628540474:ios:a4c2a76001bf2bf31a9503',
    messagingSenderId: '790628540474',
    projectId: 'waiterbook',
    storageBucket: 'waiterbook.appspot.com',
    iosClientId: '790628540474-as740n5943ahq956qgkg827jg6g7uv9n.apps.googleusercontent.com',
    iosBundleId: 'com.example.waiterbookadmin',
  );
}
